---
# Slurm config
name: "SLURM"
partition: "dev"
account: ""  # important for HHLR cluster
job-name: "cma"  # this will be the experiment's name in slurm
#experiment_copy_dst: "/home/max_li/exp_code"
path_to_template: "/home/max_li/code/cw2/cma_tutorial/sbatch_template.sh"  # TODO: get absolute path from current pwd or so
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 1
mem-per-cpu: 1000
time: 30

---
# DEFAULT
name: "DEFAULT"
repetitions: 5  # number of times one set of parameters is run
iterations: 1000  # number of iterations per repetition
path: "cmaes"
gui: false
params:
  stop_at_target: true
  target_fitness: 1.0e-5
  stop_at_divergence: true
  divergence_fitness: 1.0e+12
  optim_params:
    max_samples: 0
    x_init: 1
    init_sigma: 1
    c_sigma: ~
    d_sigma: ~
    c_mu: ~
    c_c: ~
    c_1: ~

---
name: "rosenbrock"
path: "/home/max_li/exp_output/rosenbrock/"
params:
  problem:
    name: 'rosenbrock'

list:
  budget: [10000, 20000, 40000, 60000]
  optim_params:
    n_samples: [6, 8, 10, 12]
  problem:
    dim: [2, 5, 10, 20]
