---
# Slurm config (optional)
name: "SLURM"   # MUST BE "SLURM"

# Required
partition: "dev"
job-name: "polynom"    # this will be the experiment's name in slurm
#path_to_template: "/home/max_li/code/cw2/templates/sbatch_template.sh"   # Path to YOUR prepared sbatch script

# Required - Cluster Specific
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 1
mem-per-cpu: 1000
time: 30

# Optional
venv: "/home/max_li/venv/bin/activate"   # optional. path to your virtual environment activate-file

# Optional Code Copy: Both Args are required.
#experiment_copy_dst: "/home/max_li/polylog/code"       # optional. dir TO which the current code will be copied. Useful to prevent unintentional changes while the job is in queue. Defaults to EXPERIMENTCONFIG.path/code
#experiment_copy_src: "/home/max_li/code/cw2/polynom_tutorial"       # optional. dir FROM which the current code will be copied. Useful to prevent unintentional changes while the job is in queue. Defaults to CWD.

---

# DEFAULT parameters (Optional)
name: "DEFAULT"   # MUST BE 'DEFAULT'

# Required: Can also be set in DEFAULT
path: "/home/max_li/polylog"   # location to save results in
repetitions: 2    # number of times one set of parameters is run
iterations: 1000  # number of iterations per repetition

# Implementation default parameters
params:
  noise: 5
  stepsize: 0.05

---
# Experiment 1
name: "polynomial"

params:
  x_0: 1
  x_1: 2
  x_2: 3
  x_3: 4

---
# Experiment 2
name: "grid_polynom"
repetitions: 1
iterations: 100

params:
  x_0: 2

# A total of 12 Runs will be created
grid:
  x_1: [3, 4]
  x_2: [3, 4, 5]
  x_3: [0, 1]