# DEFAULT parameters (Optional)
name: "DEFAULT"   # MUST BE 'DEFAULT'

# Implementation default parameters
params:
  noise: 0.1
  stepsize: 0.05

# Will be overwritten by named experiments.
---
# Experiment 1
name: "experiment_name"

# Required: Can also be set in DEFAULT
path: "path/to/output_dir/"   # location to save results in
repetitions: 5    # number of times one set of parameters is run
iterations: 1000  # number of iterations per repetition

# Experiment Parameters: Can also be set in DEFAULT.
# Experiment Parameters: Can also be set in DEFAULT.
params:
  x_0: 1
  x_1: 2
  x_2: 3
