---
# Slurm config (optional)
name: "SLURM"

# REQUIRED
partition: "dev"
account: ""  # important for HHLR cluster
job: "cma"    # this will be the experiment's name in slurm
path_to_template: "/path/to/sbatch_template.sh"   # Path to YOUR prepared sbatch script TODO: get absolute path from current pwd or so

# Cluster Specific
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 1
mem-per-cpu: 1000
time: 30

# Optional
experiment_copy_dst: "/path/to/code_copy/dst"   # optional. dir TO which the current code will be copied. Useful to prevent unintentional changes while the job is in queue. If not set, no copy will be made.
experiment_copy_src: "/path/to/code_copy/src"   # optional. dir FROM which the current code will be copied. Useful to prevent unintentional changes while the job is in queue. Defaults to directory of __MAIN__ file.
slurm_log: "/path/to/slurmlog/outputdir"   # optional. dir in which slurm output and error logs will be saved. Defaults to EXPERIMENTCONFIG.path

# Cluster specific options:
num_parallel_jobs: 120
number_of_jobs: 1
number_of_cpu_per_job: 1
mem: 1000
time_limit: 30

---
# DEFAULT parameters
name: "DEFAULT"
repetitions: 5  # number of times one set of parameters is run
iterations: 1000  # number of iterations per repetition
# Implementation default parameters
params:
  max_samples: 2

---
# Experiment 1
name: "experiment_name"
path: "path/to/output_dir/"   # location to save results in
params:
  problem:
    name: 'rosenbrock'

list:
  budget: [10000, 20000, 40000, 60000]
  optim_params:
    n_samples: [6, 8, 10, 12]
  problem:
    dim: [2, 5, 10, 20]
