---
# Slurm config (optional)
name: "SLURM"   # MUST BE "SLURM"

# Required
partition: "dev"
job-name: "experiment"    # this will be the experiment's name in slurm

# Required - Cluster Specific
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 1
time: 30  # Runtime in Wallclock Time. Can be int or str in form "HH:MM:SS"

mem-per-cpu: 1000 # Optional - Cluster specific

# Optional
path_to_template: "/path/to/sbatch_template.sh"     # Path to YOUR prepared sbatch script. Uses supplied default template if not specified
account: ""                                         # Account name to which Cluster Time will be booked. Cluster dependent.
slurm_log: "/path/to/slurmlog/outputdir"            # optional. dir in which slurm output and error logs will be saved. Defaults to EXPERIMENTCONFIG.path/slurmlog
venv: "/path/to/virtual_environment/bin/activate"   # optional. path to your virtual environment activate-file

# Optional Code Copy: Both Args are required.
experiment_copy_dst: "/path/to/code_copy/dst"       # optional. dir TO which the current code will be copied. Useful to prevent unintentional changes while the job is in queue.
experiment_copy_auto_dst: "/path/to/code_copy/dst"  # will autoincrement and create a dir TO which the current code will be copied. Useful to prevent unintentional changes while the job is in queue.
experiment_copy_src: "/path/to/code_copy/src"       # optional. dir FROM which the current code will be copied. Useful to prevent unintentional changes while the job is in queue.

# Optional SBATCH Arguments
sbatch_args:    # Dictionary of SBATCH keywords and arguments
  kw_1: "arg1"  # Will construct the line: #SBATCH --kw_1 arg1
  kw_2: "arg2"  # Will construct the line: #SBATCH --kw_2 arg2

# Optional shell instructions
sh_lines:       # List of strings
  - "line 1"
  - "line 2"

---
# DEFAULT parameters (Optional)
name: "DEFAULT"   # MUST BE 'DEFAULT'

# Implementation default parameters
# Will be overwritten by named experiments.
params:
  param_1: "default_value"


---
# Experiment 1
name: "experiment_name"

# Required: Can also be set in DEFAULT
path: "path/to/output_dir/"   # location to save results in
repetitions: 5    # number of times one set of parameters is run
iterations: 1000  # number of iterations per repetition

# Optional: Can also be set in DEFAULT
# Only use these values if you are sure you know what you are doing.
# Refer to Chapter 9 of the Docs for more info
reps_per_job: 1    # number of repetitions in each job. useful for paralellization. defaults to 1.
reps_in_parallel: 1 # number of repetitions in each job that are executed in parallel. defaults to 1.

# Experiment Parameters: Can also be set in DEFAULT.
params:
  param_1: "exp_value_1" # overwrites Default
  param_2: "exp_value_2" # new experiment specific parameter

# Dynamically assigned parameters. Can be EITHER 'list' or 'grid'. Can NOT be set in DEFAULT. Can be a nested dictionary.
list:   # alternative - 'grid:'
  param_3: [1, 2]
  param_4: [3, 4]
